platform :ios, '15.0'

target 'AppTest' do
  use_frameworks!

  # Networking
  pod 'Alamofire', '~> 5.5.0'
  pod 'Moya', '~> 15.0.0'
  
  # UI
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  
  # Utils
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'KeychainAccess', '~> 4.2.2'
  
  # Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  
  # Vulnerable dependency (intentional for testing)
  pod 'AFNetworking', '2.5.0'  # Known vulnerability for testing
  
  target 'AppTestTests' do
    inherit! :search_paths
    pod 'Quick', '~> 5.0.0'
    pod 'Nimble', '~> 10.0.0'
  end

  target 'AppTestUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end 